{
    "docs": "https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.7` [[explain](https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/import.html)] failed with 2 errors:", 
            "output": "plugins/module_utils/haproxy.py:8:0: traceback: ModuleNotFoundError: No module named 'commons'\nplugins/modules/haproxy_backend.py:136:0: traceback: ModuleNotFoundError: No module named 'commons' (at plugins/module_utils/haproxy.py:8:0)"
        }
    ], 
    "verified": false
}
